spring.application.name=payment-service

server.port=8082

spring.datasource.url=jdbc:mysql://localhost:3308/payment_service_db
spring.datasource.username=root
spring.datasource.password=Thisismanmad1@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#payment creates and send events to these queues
order.payment.completed.queue.name=order.payment.completed.queue
notification.payment.completed.queue.name=notification.payment.completed.queue

#using these routing keys
order.payment.completed.routing.key=order.payment.completed.key
notification.payment.completed.routing.key=notification.payment.completed.key

#via this exchange
payment.exchange.name=payment.exchange

#payment consumer consumes from this queue
payment.order.created.queue.name=payment.order.created.queue

