spring.application.name=order-service

server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3308/order_service_db
spring.datasource.username=root
spring.datasource.password=Thisismanmad1@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#order creates and sends event to these queues
payment.order.created.queue.name=payment.order.created.queue
notification.order.created.queue.name=notification.order.created.queue

#using these routing keys
payment.order.created.routing.key=payment.order.created.key
notification.order.created.routing.key=notification.order.created.key

#via this exchange
order.exchange.name=order.exchange

#order consumer consume from this queue
order.payment.completed.queue.name=order.payment.completed.queue